// POSTS ACTIONS
export const GET_POSTS = 'GET_POSTS';
export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

// SYSTEM ACTIONS
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// USERS ACTIONS
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

