# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'albums' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for albums
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'

  rn_path = '../node_modules/react-native'
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]

  target 'albumsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'albums-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for albums-tvOS

  target 'albums-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
